//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by VDrawRes.rc
//
#define IDS_VDRAW4                      1
#define IDD_ABOUTBOX_VDRAW4             1
#define IDB_VDRAW4                      1
#define IDI_ABOUTDLL                    1
#define IDS_VDRAW4_PPG                  2
#define IDC_REGISTER                    2
#define IDNEW                           3
#define IDNEXT                          3
#define IDC_SELECTPRINTER               3
#define IDS_VDRAWNET                    3
#define IDS_VDRAWI                      3
#define ID_CURENT                       3
#define IDBYVCI                         3
#define IDTRUECOLOR                     3
#define IDDELETE                        4
#define IDPREV                          4
#define IDS_VDRAW4_PPGNET               4
#define ID_DEL                          4
#define IDFREEZE                        5
#define IDS_VDRAWVIEW                   5
#define ID_NEW                          5
#define ID_CURRENT                      6
#define IDTHAW                          7
#define IDCOLOR                         8
#define IDSELECTALL                     9
#define IDDESELECT                      10
#define IDLTYPE                         11
#define IDLOCK                          12
#define IDUNLOCK                        13
#define IDS_VDRAW4_PPG_CAPTION          100
#define IDD_PROPPAGE_VDRAW4             100
#define ID_INDICATOR_COORD              101
#define ID_INDICATOR_SNAP               102
#define IDS_VDRAWHELP                   103
#define IDS_message1                    104
#define IDS_message2                    105
#define IDS_message3                    106
#define IDS_message4                    107
#define IDS_message5                    108
#define IDS_message6                    109
#define IDS_message7                    110
#define IDS_message8                    111
#define IDS_message9                    112
#define IDS_message10                   113
#define IDS_message11                   114
#define IDS_message12                   115
#define IDS_message13                   116
#define IDS_message14                   117
#define IDS_message15                   118
#define IDS_message16                   119
#define IDS_message17                   120
#define IDS_message18                   121
#define IDS_message19                   122
#define IDS_message20                   123
#define IDS_message21                   124
#define IDS_message22                   125
#define IDS_message23                   126
#define IDS_message24                   127
#define IDS_message25                   128
#define IDS_message26                   129
#define IDS_message27                   130
#define IDS_message28                   131
#define IDS_message29                   132
#define IDS_message30                   133
#define IDS_message31                   134
#define IDS_message32                   135
#define IDS_message33                   136
#define IDS_message34                   137
#define IDS_message35                   138
#define IDS_message36                   139
#define IDS_message37                   140
#define IDS_message38                   141
#define IDS_message39                   142
#define IDS_message40                   143
#define IDS_message41                   144
#define IDS_message42                   145
#define IDS_message43                   146
#define IDS_message44                   147
#define IDS_message45                   148
#define IDS_message46                   149
#define IDS_message47                   150
#define IDS_message48                   151
#define IDS_message49                   152
#define IDS_message50                   153
#define IDS_message51                   154
#define IDS_message52                   155
#define IDS_message53                   156
#define IDS_message54                   157
#define IDS_message55                   158
#define IDS_message56                   159
#define IDS_message57                   160
#define IDS_message58                   161
#define IDS_message59                   162
#define IDS_VDRAW4_PPGFNAME             163
#define IDS_VDRAW4_PPGFNAMEFMP          164
#define IDS_VDPPGFILES                  165
#define IDS_VDPPGFILESCAPTION           166
#define IDS_VDPPGPALETTE                167
#define IDS_VDPPGPALETTECAP             168
#define IDS_message60                   169
#define IDS_VDPPGABOUT                  170
#define IDS_VDPPGABOUTCAP               171
#define IDS_VDPPGDWG                    172
#define IDS_VDPPGDWGCAP                 173
#define IDS_message61                   174
#define IDS_VDRAW4_PPGVDRAWRES          175
#define IDS_message62                   176
#define IDS_STATBARSNAP1                177
#define IDS_STATBARSNAP0                178
#define IDS_STATBARGRID1                179
#define IDS_STATBARGRID0                180
#define IDS_STATBARORTHO1               181
#define IDS_STATBARORTHO0               182
#define IDS_STATBAROSNAP1               183
#define IDS_STATBAROSNAP0               184
#define IDS_message63                   185
#define IDS_VDPPGMATERIAL               186
#define IDS_message64                   187
#define IDS_message65                   188
#define IDS_message66                   189
#define IDS_message67                   190
#define IDS_message68                   191
#define IDS_message69                   192
#define IDS_message70                   193
#define IDS_message71                   194
#define IDS_message72                   195
#define IDS_message73                   196
#define IDS_message74                   197
#define IDS_message75                   198
#define IDS_message76                   199
#define IDS_message77                   200
#define IDS_message78                   201
#define IDC_COMBO1                      202
#define IDD_PREVIEWDLG                  202
#define IDS_message79                   202
#define IDC_EDIT1                       203
#define IDC_NULLCURSOR                  203
#define IDS_message80                   203
#define IDC_EDIT2                       204
#define IDD_OSNAPDIALOG                 204
#define IDS_message81                   204
#define IDC_CHECK1                      205
#define IDC_VAL3                        205
#define IDC_SCALEX                      205
#define IDC_PRINTERMM                   205
#define IDS_message82                   205
#define IDC_CHECK2                      206
#define IDC_PREVIEWWIN                  206
#define IDC_VAL4                        206
#define IDC_ROTATION                    206
#define IDS_message83                   206
#define IDC_EDIT3                       207
#define IDC_CHECK3                      207
#define IDD_LAYERDLG                    207
#define IDC_DRAWUNT                     207
#define IDS_message84                   207
#define IDC_BUTTON1                     208
#define IDC_CHECK4                      208
#define IDD_COLORDIALOG                 208
#define IDS_message85                   208
#define IDC_CHECK5                      209
#define IDD_EDIT_ATTRIB                 209
#define IDC_SCALEY                      209
#define IDC_COL6                        209
#define IDC_EDIT5                       209
#define IDS_message86                   209
#define IDC_CHECK6                      210
#define IDB_HATCH1                      210
#define IDC_BUTTON4                     210
#define IDS_message87                   210
#define IDC_BUTTON2                     211
#define IDB_HATCH2                      211
#define IDC_CHECK7                      211
#define IDS_message88                   211
#define IDC_LIST1                       212
#define IDB_HATCH3                      212
#define IDC_CHECK8                      212
#define IDS_message89                   212
#define IDC_CURRENTName                 213
#define IDD_INSERTDIALOG                213
#define IDC_CHECK10                     213
#define IDS_message90                   213
#define IDC_NEW                         214
#define IDC_EDIT4                       214
#define IDS_message91                   214
#define IDC_CHECK12                     214
#define IDD_EVALUATION                  215
#define IDC_CHECK9                      215
#define IDS_message92                   215
#define IDC_CHECK13                     215
#define IDS_message93                   216
#define IDC_CHECK11                     216
#define IDC_COLORCOMBO                  217
#define IDS_message94                   217
#define IDC_BUTTON7                     217
#define IDC_TAG1                        218
#define IDS_message95                   218
#define IDC_TAG2                        219
#define IDS_message96                   219
#define IDC_TAG3                        220
#define IDS_message97                   220
#define IDC_TAG4                        221
#define IDS_message98                   221
#define IDC_TAG5                        222
#define IDS_message99                   222
#define IDC_VAL1                        223
#define IDS_message100                  223
#define IDC_VAL2                        224
#define IDD_PEN_ASSIGNMENTS             224
#define IDS_message101                  224
#define IDC_VAL5                        225
#define IDS_message102                  225
#define IDC_BLOCKNAME                   226
#define IDS_message103                  226
#define IDS_message104                  227
#define IDC_INSX                        228
#define IDS_message106                  228
#define IDC_INSY                        229
#define IDS_message107                  229
#define IDC_SELECTFILE                  230
#define IDR_POPMENUZOOMPRINT            230
#define IDS_message108                  230
#define IDC_FILENAME                    231
#define IDS_message109                  231
#define IDC_BLOCKLIST                   232
#define IDS_message110                  232
#define IDC_RADIOBLOCK                  233
#define IDC_CURSORPAN                   233
#define IDS_message111                  233
#define IDC_RADIOFILE                   234
#define IDS_message112                  234
#define IDC_PARAMONSCREEN               235
#define IDD_PROPNONE                    235
#define IDS_message113                  235
#define IDD_CUSTOPEN                    236
#define IDS_message114                  236
#define IDC_RADIO1                      237
#define IDD_SELECTCOLOR                 237
#define IDS_message115                  237
#define IDC_RADIO2                      238
#define IDD_VDPROPFILES                 238
#define IDS_message116                  238
#define IDC_PICKWINDOW                  239
#define IDD_VDPALETTEPROP               239
#define IDS_message117                  239
#define IDC_ORIGINX                     240
#define IDB_ABOUT1                      240
#define IDC_LEFT                        240
#define IDS_message118                  240
#define IDC_ORIGINY                     241
#define IDD_VDABOUTPPG                  241
#define IDC_TOP                         241
#define IDS_message119                  241
#define IDC_FIT                         242
#define IDD_VDPROPDWG                   242
#define IDS_message120                  242
#define IDC_BW                          243
#define IDS_message121                  243
#define IDC_UPDATEVIEW                  244
#define IDD_LINETYPEDLG                 244
#define IDS_message122                  244
#define IDC_NUM1                        245
#define IDC_RIGHT                       245
#define IDS_message123                  245
#define IDC_TISOFTLOGO                  246
#define IDC_BOTTOM                      246
#define IDS_message124                  246
#define IDC_RADIO3                      247
#define IDS_CMDPL_INITUSERGET_1         247
#define IDC_RADIO4                      248
#define IDS_CMDPL_INITUSERGET_2         248
#define IDC_COLOR                       249
#define IDC_RADIO6                      249
#define IDS_CMDPL_INITUSERGET_3         249
#define IDC_WIDTH                       250
#define IDC_RADIO7                      250
#define IDS_CMDPL_MSG_1                 250
#define IDC_PENASSIGN                   251
#define IDR_ADINITDAT                   251
#define IDS_CMDPL_MSG_2                 251
#define IDC_SCFIT                       252
#define IDS_CMDPL_MSG_3                 252
#define IDC_PRODUCTID                   253
#define IDS_CMDPL_MSG_4                 253
#define IDC_SERNUM                      254
#define IDS_CMDPL_MSG_5                 254
#define IDC_PREVIEW                     255
#define IDC_CURSOR3DROT                 255
#define IDS_CMDPL_MSG_6                 255
#define IDC_COL240                      256
#define IDC_HANDPOINT                   256
#define IDS_CMDPL_MSG_7                 256
#define IDC_GRIPCOLOR                   257
#define IDS_CMDPL_MSG_8                 257
#define IDC_BYLAYER                     258
#define IDC_COL10                       259
#define IDC_BUTTON3                     260
#define IDC_BYBLOCK                     260
#define IDC_GRIPCOL                     261
#define IDC_PALETTE240                  262
#define IDC_PALETTE6                    263
#define IDB_STAT_ZOOM_W                 263
#define IDC_PALETTE9                    264
#define IDB_STAT_REDRAW                 264
#define IDB_STAT_VTOP                   265
#define IDB_STAT_RENDER                 266
#define IDB_STAT_LAYERS                 267
#define IDB_STAT_OPEN                   268
#define IDC_CHROMA                      269
#define IDB_STAT_PRINT                  269
#define IDB_STAT_PAN                    270
#define IDC_COLNO                       271
#define IDB_STAT_ZE                     271
#define IDB_STAT_ZP                     272
#define IDB_STAT_ZIN                    273
#define IDB_STAT_ZOUT                   274
#define IDB_STAT_ZALL                   275
#define IDB_STAT_VBOTTOM                276
#define IDC_CHOOSECOLOR                 277
#define IDB_STAT_VLEFT                  277
#define IDC_RESET                       278
#define IDB_STAT_VRIGHT                 278
#define IDC_STATICGRPSZ                 279
#define IDB_STAT_VFRONT                 279
#define IDC_COMBO2                      280
#define IDB_STAT_VIEWBACK               280
#define IDB_STAT_VSW                    281
#define IDB_STAT_VSE                    282
#define IDB_STAT_VNE                    283
#define IDB_STAT_VNW                    284
#define IDB_STAT_SHADE                  286
#define IDB_STAT_SHADEON                287
#define IDB_STAT_HIDE                   288
#define IDB_STAT_WIRE                   289
#define IDB_STAT_VROT                   290
#define IDB_STAT_PLANW                  291
#define IDB_STAT_VDINAMIC               292
#define IDC_LIST2                       298
#define IDC_LIST                        301
#define IDB_LAYFREEZE                   304
#define IDB_LAYTHAW                     305
#define IDC_PRINTUNIT_TYPE              305
#define IDB_LAYLOCK                     306
#define IDB_LAYUNLOCK                   307
#define IDC_EDIT_PWD                    307
#define IDB_STAT_CLIP_CUT               308
#define IDC_PASS_FILE_NAME              308
#define IDB_STAT_CLIP_COPY              309
#define IDB_STAT_CLIP_PASTE             310
#define IDD_LAYOUTS                     315
#define IDD_LAYOUTNEW                   316
#define IDB_STAT_LAYOUTS                317
#define IDD_LW                          318
#define IDD_HATCHPATTERNDLG             347
#define IDD_CHOOSECOLOR                 348
#define IDD_PASSWORD_DLG                349
#define COLOR_LUMSCROLL                 702
#define COLOR_HUE                       703
#define COLOR_SAT                       704
#define COLOR_LUM                       705
#define COLOR_RED                       706
#define COLOR_GREEN                     707
#define COLOR_BLUE                      708
#define COLOR_CURRENT                   709
#define COLOR_RAINBOW                   710
#define COLOR_ADD                       712
#define COLOR_SOLID                     713
#define COLOR_MIX                       719
#define COLOR_BOX1                      720
#define COLOR_CUSTOM1                   721
#define COLOR_HUEACCEL                  723
#define COLOR_SATACCEL                  724
#define COLOR_LUMACCEL                  725
#define COLOR_REDACCEL                  726
#define COLOR_GREENACCEL                727
#define COLOR_BLUEACCEL                 728
#define COLOR_SOLID_LEFT                730
#define COLOR_SOLID_RIGHT               731
#define ID_PMNUZOOM_W                   32769
#define ID_VDCOMMANDS_ZOOM_W            32769
#define ID_PMNUZOOM_P                   32770
#define ID_VDCOMMANDS_ZOOM_P            32770
#define ID_PMNUZOOM_E                   32771
#define ID_VDCOMMANDS_ZOOM_E            32771
#define ID_PMNUPRINT                    32772
#define IDPRINT                         32772
#define ID_PAN                          32774
#define ID_ZOOMIN                       32775
#define ID_ZOOMOUT                      32776
#define ID_NETPOPUPEXIT                 32777
#define IDLAYERS                        32778
#define ID_VDCOMMANDS_HIDE              32780
#define ID_VDCOMMANDS_SHADE             32781
#define ID_VDCOMMANDS_RENDER            32782
#define ID_VDCOMMANDS_3DVIEW_TOP        32783
#define ID_VDCOMMANDS_3DVIEW_BOTTOM     32784
#define ID_VDCOMMANDS_3DVIEW_LEFT       32785
#define ID_VDCOMMANDS_3DVIEW_RIGHT      32786
#define ID_VDCOMMANDS_3DVIEW_FRONT      32787
#define ID_VDCOMMANDS_3DVIEW_BACK       32788
#define ID_VDCOMMANDS_3DVIEW_SWISOMETRIC 32789
#define ID_VDCOMMANDS_3DVIEW_SEISOMETRIC 32790
#define ID_VDCOMMANDS_3DVIEW_NEISOMETRIC 32791
#define ID_VDCOMMANDS_3DVIEW_NWISOMETRIC 32792
#define ID_VDCOMMANDS_3DVIEW_DYNAMIC    32793
#define ID_VDCOMMANDS_EXIT              32794
#define ID_VDCOMMANDS_REGEN             32795
#define ID_VDCOMMANDS_REDRAW            32796
#define ID_VDCOMMANDS_ZOOM_ALL          32797
#define ID_VDCOMMANDS_SHADEEDGEON       32798
#define ID_VDCOMMANDS_3DVIEW_PLANWORLD  32799
#define ID_VDCOMMANDS_OPEN              32800
#define ID_VDCOMMANDS_WIRE              32802
#define ID_VDCOMMANDS_CLIPBOARD_CUT     32803
#define ID_VDCOMMANDS_CLIPBOARD_COPY    32804
#define ID_VDCOMMANDS_CLIPBOARD_PASTE   32805
#define IDLAYOUTS                       32806
#define IDS_LT_BYLAYER                  32807
#define IDS_LT_BYBLOCK                  32808
#define IDS_LT_CONTINUOUS               32809
#define IDS_LT_APIDASH                  32810
#define IDS_LT_APIDOT                   32811
#define IDS_LT_APIDASHDOT               32812
#define IDS_LT_APIDOTDOT                32813

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        254
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         281
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
